# Generated by Django 3.2.8 on 2021-11-11 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_forma_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='forma',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
